services:
  spacetimedb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./world-simulation:/app/world-simulation
      - spacetime-data:/root/.local/share/spacetime/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  spacetime-data: