[package]
name = "world-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb = "1.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
log = "0.4"

[lib]
crate-type = ["cdylib"]